style:
  MaxLineLength:
    maxLineLength: 150

complexity:
  LongParameterList:
    active: true
    functionThreshold: 7
    ignoreDefaultParameters: true

formatting:
  MultiLineIfElse:
    active: false
